name: Check

on:
  workflow_call:

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0

  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - run: go test ./parser/...

  lint-vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm run check

  test-vscode:
    needs:
      - test-go
    strategy:
      matrix:
        include:
          - target: linux-arm64
            os: ubuntu-latest
            npm_config_arch: arm64
          - target: linux-x64
            os: ubuntu-latest
            npm_config_arch: x64
          - target: darwin-arm64
            os: macos-latest
            npm_config_arch: arm64
          - target: win32-arm64
            os: windows-latest
            npm_config_arch: arm
          - target: win32-x64
            os: windows-latest
            npm_config_arch: x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm install
        env:
          npm_config_arch: ${{ matrix.npm_config_arch }}
      - run: pnpm run test:ci
        env:
          TARGET: ${{ matrix.target }}
