name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/check.yaml

  build:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yaml
